apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-staging
resources:
  - namespace.yaml
  - ../../applications/base
images:
- {name: platform-frontend, newName: 221082176287.dkr.ecr.ca-central-1.amazonaws.com/portfolio-dev/platform-frontend, newTag: "build-14"}
- {name: platform-api, newName: 221082176287.dkr.ecr.ca-central-1.amazonaws.com/portfolio-dev/platform-api, newTag: "build-14"}
- {name: platform-auth, newName: 221082176287.dkr.ecr.ca-central-1.amazonaws.com/portfolio-dev/platform-auth, newTag: "build-14"}
- {name: platform-worker, newName: 221082176287.dkr.ecr.ca-central-1.amazonaws.com/portfolio-dev/platform-worker, newTag: "build-14"}
replicas:
- {name: api, count: 2}
- {name: frontend, count: 2}

patches:
  - path: ingress-platform-host.yaml
    target:
      kind: Ingress
      name: platform
  - path: ingress-services-host.yaml
    target:
      kind: Ingress
      name: platform-services

