apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../applications/base]
images:
- {name: platform-frontend, newName: alexcgodwin/platform-frontend, newTag: "1"}
- {name: platform-api, newName: alexcgodwin/platform-api, newTag: "1"}
- {name: platform-auth, newName: alexcgodwin/platform-auth, newTag: "1"}
- {name: platform-worker, newName: alexcgodwin/platform-worker, newTag: "1"}
replicas:
- {name: api, count: 2}
- {name: frontend, count: 2}
