apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../applications/base

images:
  - name: platform-frontend
    newName: 221082176287.dkr.ecr.ca-central-1.amazonaws.com/portfolio-dev/platform-frontend
    newTag: "v2"

  - name: platform-api
    newName: 221082176287.dkr.ecr.ca-central-1.amazonaws.com/portfolio-dev/platform-api
    newTag: "v2"

  - name: platform-auth
    newName: 221082176287.dkr.ecr.ca-central-1.amazonaws.com/portfolio-dev/platform-auth
    newTag: "v2"

  - name: platform-worker
    newName: 221082176287.dkr.ecr.ca-central-1.amazonaws.com/portfolio-dev/platform-worker
    newTag: "v2"

replicas:
  - name: frontend
    count: 1